# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Andreas Nõmm
email: andy@andyiam.com
description: > # this means to ignore newlines until "baseurl:"
  Business Information Technologist. My blog about software, business,
  personal growth, art, social agendas. "Think big, act bigger".
baseurl: "" # the subpath of your site, e.g. /blog
url: andyiam.com # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: andyiamcom
github_username:  andyiamcom

# Build settings
markdown: kramdown
